repository: callistaenterprise/blog-microservices
current_version: "v5.2.0.202406240805"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
