repository: anilallewar/microservices-basics-spring-boot
current_version: "v5.2.0.202402260843"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
