repository: anilallewar/microservices-basics-spring-boot
current_version: "v5.1.0.202312201344"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
