repository: anilallewar/microservices-basics-org.palladiosimulator.somox.analyzer.rules.impl.spring-boot
current_version: "v5.1.0.202309251236"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
