repository: rohitghatol/spring-boot-microservices
current_version: "v5.2.0.202401250907"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
