repository: rohitghatol/spring-boot-microservices
current_version: "v5.1.0.202312180857"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
