repository: rohitghatol/org.palladiosimulator.somox.analyzer.rules.impl.spring-boot-microservices
current_version: "v5.1.0.202309251236"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
