repository: kit-recipe-app/recipebackendnew
current_version: "v5.2.0.202401150907"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
