repository: mdeket/spring-cloud-movie-recommendation
current_version: "v5.1.0.202312201344"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
