repository: mdeket/spring-cloud-movie-recommendation
current_version: "v5.2.0.202403180840"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
