repository: corona-warn-app/cwa-verification-server
current_version: "v5.2.0.202402260843"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
