repository: georgwittberger/apache-spring-boot-microservice-example
current_version: "v5.2.0.202408070511"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
