repository: georgwittberger/apache-org.palladiosimulator.somox.analyzer.rules.impl.spring-boot-microservice-example
current_version: "v5.1.0.202309251236"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
