repository: teammates/teammates
current_version: "v5.2.0.202408280745"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.jax_rs
  - org.palladiosimulator.retriever.extraction.rules.ecmascript
