repository: kbastani/spring-cloud-event-sourcing-example
current_version: "v5.2.0.202408280745"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
