repository: kbastani/org.palladiosimulator.somox.analyzer.rules.impl.spring-cloud-event-sourcing-example
current_version: "v5.1.0.202309251236"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
