repository: kbastani/spring-cloud-event-sourcing-example
current_version: "v5.1.0.202312180857"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
