repository: yidongnan/spring-cloud-netflix-example
current_version: "v5.2.0.202406050756"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
