repository: yidongnan/spring-cloud-netflix-example
current_version: "v5.1.0.202312191041"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
  - org.palladiosimulator.somox.analyzer.rules.impl.ecmascript
