repository: descartesresearch/teastore
current_version: "v5.2.0.202408070511"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.jax_rs
  - org.palladiosimulator.retriever.extraction.rules.ecmascript
