repository:
  - corona-warn-app/cwa-dcc-server
  - corona-warn-app/cwa-log-upload
  - corona-warn-app/cwa-map-public-frontend
  - corona-warn-app/cwa-ppa-server
  - corona-warn-app/cwa-registrierung
  - corona-warn-app/cwa-server
  - corona-warn-app/cwa-testresult-server
  - corona-warn-app/cwa-verification-portal
  - corona-warn-app/cwa-verification-server
  - corona-warn-app/cwa-website
current_version: "v5.2.0.202402260843"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
