repository:
  - corona-warn-app/cwa-dcc-server
  - corona-warn-app/cwa-log-upload
  - corona-warn-app/cwa-ppa-server
  - corona-warn-app/cwa-server
  - corona-warn-app/cwa-testresult-server
  - corona-warn-app/cwa-verification-portal
  - corona-warn-app/cwa-verification-server
current_version: "v5.2.0.202408041728"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
