repository: meet-eat/meet-eat-server
current_version: "v5.2.0.202408070511"
rules:
  - org.palladiosimulator.retriever.extraction.rules.gradle
  - org.palladiosimulator.retriever.extraction.rules.spring
