repository: meet-eat/meet-eat-server
current_version: "v5.1.0.202312191012"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.gradle
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
  - org.palladiosimulator.somox.analyzer.rules.impl.ecmascript
