repository: shabbirdwd53/springboot-microservice
current_version: "v5.2.0.202408070511"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
