repository: shabbirdwd53/springboot-microservice
current_version: "v5.1.0.202312201344"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
  - org.palladiosimulator.somox.analyzer.rules.impl.ecmascript
