repository:
  - openmrs/openmrs-core
  - openmrs/openmrs-module-webservices.rest
current_version: v5.1.0.202312180857
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
