repository: corona-warn-app/cwa-ppa-server
current_version: "v5.2.0.202404221423"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
