repository: corona-warn-app/cwa-dcc-server
current_version: "v5.2.0.202407010739"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
