repository: fernandoabcampos/spring-netflix-oss-microservices
current_version: "v5.2.0.202403250833"
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
