repository: webgoat/webgoat
current_version: v5.1.0.202312191041
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
  - org.palladiosimulator.somox.analyzer.rules.impl.ecmascript
