repository: org.palladiosimulator.somox.analyzer.rules.impl.spring-petclinic/org.palladiosimulator.somox.analyzer.rules.impl.spring-petclinic-microservices
current_version: "v5.1.0.202309251236"
rules:
  - org.palladiosimulator.somox.analyzer.rules.impl.maven
  - org.palladiosimulator.somox.analyzer.rules.impl.spring
