repository: cloudscale-project/cloudstore
current_version: v5.2.0.202402260843
rules:
  - org.palladiosimulator.retriever.extraction.rules.maven
  - org.palladiosimulator.retriever.extraction.rules.spring
